api:
  searchPageSize: 100
  searchLimitCount: 1000
  fofa:
    key: yiheng6221@163.com:093208d32a4b0202b925240b81e9b739
  #key: ying.hu@qingteng.cn:00954c8731415dfe6cd7f97820c4ce10
  icp:
    key: ""
  quake:
    key: ""
  hunter:
    key: ""

onlineapi:
  fofa: true
  quake: false
  hunter: false

mysql:
  host: 127.0.0.1
  port: 3306
  name: Findyou
  username: nbanb
  password: nbanbpro

redis:
  host: 127.0.0.1:6379
  password: nbanbpro

#写入redis的数据每条最多多少个
splittodb:
  fofakeyword: 100
  hunterkeyword: 100
  quakekeyword: 100
  #根据workflow个数
  targets: 500
  fingers: 100

blacklist:
  - "online.nl"
  - "xxxx"