目标:
  名称:
    - "上海壹佰米网络科技有限公司"
    - "超荔志（无锡）电子商务有限公司"
    - "上海吃之以恒农业科技有限公司"
    - "柿柿顺（南京）电子商务有限公司"
    - "有菱感（江苏）电子商务有限公司"
    - "有菱感（厦门）电子商务有限公司"
    - "重庆超荔志电子商务有限公司"
    - "上海春风十里农业有限公司"
    - "三河吃之以恒电子商务有限公司"
    - "东莞食来运转电子商务有限公司"
    - "佛山超荔志电子商务有限公司"
    - "成都吃之以恒电子商务有限公司"
    - "上海雨生百谷食品有限公司"
    - "上海生润香往食品科技有限公司"
    - "上海金山生润香往食品有限公司"
    - "上海美丽早晨食品科技有限公司"
    - "上海活灵活现食品科技有限公司"
    - "上海好客田园食品科技有限公司"
    - "马鞍山吃之以恒电子商务有限公司"
    - "超荔志（南京）电子商务有限公司"
    - "有菱感（广州）电子商务有限公司"
    - "群樱汇（上海）电子商务有限公司"
    - "北京不姜就电子商务有限公司"
    - "上海柿柿顺物流有限公司"
    - "食来运转（上海）电子商务有限公司"
    - "柿柿顺（江苏）电子商务有限公司"
    - "柿柿顺（深圳）电子商务有限公司"
    - "食来运转（杭州）电子商务有限责任公司"
    - "吃之以恒（江苏）电子商务有限公司"
    - "吃之以恒（上海）电子商务有限公司"
    - "依横依竖（上海）电子商务有限公司"
    # 目标域名:xxx.com:xxx公司
  域名:
    - "ddfresh.net:上海壹佰米网络科技有限公司"
    - "100.me:上海壹佰米网络科技有限公司"
    - "ddmaicai.mobi:上海壹佰米网络科技有限公司"
    - "imaicai.mobi:上海壹佰米网络科技有限公司"
    - "ddmaicai.net:上海壹佰米网络科技有限公司"
    - "ddfresh.mobi:上海壹佰米网络科技有限公司"
    - "ddxq.mobi:上海壹佰米网络科技有限公司"
    - "ddlfresh.com:上海壹佰米网络科技有限公司"
    - "dingdongxiaoqu.com:上海壹佰米网络科技有限公司"
    - "ddmc.mobi:上海壹佰米网络科技有限公司"
    - "ddcorp.net:上海壹佰米网络科技有限公司"
    - "ddmaicai.mobi:上海壹佰米网络科技有限公司"
    - "imaicai.mobi:上海壹佰米网络科技有限公司"
    - "ddmaicai.net:上海壹佰米网络科技有限公司"
    - "dingdongxiaoman.com:上海吃之以恒农业科技有限公司"
    - "yushengbaigu.cn:上海雨生百谷食品有限公司"
  # 目标IP:x.x.x.x:xx公司
  ip:
    - ""
  cert:
  city:
    - ""
  #默认是或的关系，在个别里面加&&可以实现语句与关系
  gobal_keyword:
    - "叮咚买菜"
    - "生润香往"
    - "超荔志"
    - "壹佰米&&物流"
    - "壹佰米&&食品"
    - "有菱感"
    - "柿柿顺"
    - "不姜就"
    - "吃之以恒"

自定义扫描:
  # 语法自定义:
  #  - body="kkkkkk"
  #  - title="kkkkkk"
  fofa:
    - #为了方便回溯归属，注意用Findyou分割
    - ""
  hunter:
    -
    -
    -
  quake:
    - ""
    -

其他扫描选项:
  跳过配置从数据库扫描: false
  生成扩展的domainsearch: true