目标:
  名称:
    - "中国太平洋保险（集团）股份有限公司"
    - "南京太保二期大健康产业基金管理合伙企业（有限合伙）"
    - "太保科技有限公司"
    - "太平洋健康保险股份有限公司"
    - "太平洋保险在线服务科技有限公司"
    - "太平洋保险代理有限公司"
    - "太积（上海）信息技术有限公司"
    - "太平洋资产管理有限责任公司"
    - "太保私募基金管理有限公司"
    - "上海广慈太保互联网医院有限公司"
    - "中国太平洋财产保险股份有限公司"
    - "上海太保不动产经营管理有限公司"
    # 目标域名:xxx.com:xxx公司
  域名:
    - "cpic.com.cn:中国太平洋保险（集团）股份有限公司"
    - "ecpic.com.cn:中国太平洋保险（集团）股份有限公司"
    - "ecpic.cn:中国太平洋保险（集团）股份有限公司"
    - "aaic.com.cn:中国太平洋保险（集团）股份有限公司"
    - "cj-pension.com.cn:中国太平洋保险（集团）股份有限公司"
    - "95500.com.cn:中国太平洋保险（集团）股份有限公司"
    - "cpiccdn.com:中国太平洋保险（集团）股份有限公司"
    - "cpicpay.cn:中国太平洋保险（集团）股份有限公司"
    - "10108888.com.cn:中国太平洋保险（集团）股份有限公司"
    - "601601.com:太平洋保险在线服务科技有限公司"
    - "cpicagency.com.cn:太平洋保险代理有限公司"
    - "gctb-hospital.cn:上海广慈太保互联网医院有限公司"
    - "gctbhy.cn:上海广慈太保互联网医院有限公司"
  # 目标IP:x.x.x.x:xx公司
  ip:
  cert:
  city:
    - ""
  #默认是或的关系，在个别里面加&&可以实现语句与关系
  gobal_keyword:
    - "太平洋"
    - "太保"
    - "保险"


自定义扫描:
  # 语法自定义:
  #  - body="kkkkkk"
  #  - title="kkkkkk"
  fofa:
    - #为了方便回溯归属，注意用Findyou分割
  hunter:
    -
    -
    -
  quake:
    - ""
    -

其他扫描选项:
  跳过配置从数据库扫描: false
  生成扩展的domainsearch: true