目标:
  名称:
    # 目标域名:xxx.com:xxx公司
    - "江苏苏豪智能科技有限公司"
    - "江苏省对外经贸股份有限公司"

  域名:
  # 目标IP:x.x.x.x:xx公司
  - "jsft.com:江苏苏豪智能科技有限公司"
  ip:
  cert:
  city:
  #默认是或的关系，在个别里面加&&可以实现语句与关系
  gobal_keyword:
    - "苏豪"
自定义扫描:
  # 语法自定义:
  #  - body="kkkkkk"
  #  - title="kkkkkk"
  fofa:
    #为了方便回溯归属，注意用Findyou分割
  hunter:
  quake:

其他扫描选项:
  跳过配置从数据库扫描: false
  生成扩展的domainsearch: true