api:
  #一次搜索的数据量大小
  searchPageSize: 100
  searchLimitCount: 1000
  fofa:
    #邮箱:apikey
    key:
  icp:
    key: ""
  quake:
    key: ""
  hunter:
    key: ""

#设置是否启用fofa、quake、hunter搜索，启动后将生成对应的搜索引擎语法和搜索任务
onlineapi:
  fofa: true
  quake: false
  hunter: false

mysql:
  host: 127.0.0.1
  port: 3306
  name: Findyou
  username: findyou
  password: findyou

redis:
  host: 127.0.0.1:6379
  password: findyou

#写入到redis的任务根据多少数量进行分割
splittodb:
  fofakeyword: 100
  hunterkeyword: 100
  quakekeyword: 100
  targets: 500
  fingers: 100
