目标:
  名称:
    - "泓书信息科技"
    - "友趣视频"
    # 目标域名:xxx.com,xxx.com,xxx.com
  域名:
    - "youyoushipin.top:泓书信息科技"
    -
  ip:
    - "1.1.1.1:泓书信息科技"
  cert:
  city:
    - "上海"
  gobal_keyword:
    - "视频"
    - "小红书"
    - "友趣"
    - "系统"

自定义扫描:
  # 语法自定义:
  #  - body="kkkkkk"
  #  - title="kkkkkk"
  fofa:
    - #为了方便回溯归属，注意用Findyou分割
    - ""
  hunter:
    -
    -
    -
  quake:
    - ""
    -
  递归搜索等级: 2

其他扫描选项:
  跳过配置从数据库扫描: false

