目标:
  名称:
    - "招商银行股份有限公司"
    - "招银理财有限责任公司"
    - "天津粤发股权投资基金合伙企业（有限合伙）"
    - "招联消费金融股份有限公司"
    - "招银金融租赁有限公司"
    - "深圳前海悠行租赁有限公司"
    - "招银神州悠行租赁有限公司"
    - "南京招银神州悠行融资租赁有限公司"
    - "招银安行租赁有限公司"
    - "招赢神州悠行汽车租赁有限公司"
    - "上海招银申三设备租赁有限公司"
    - "招银津三设备租赁有限公司"
    - "招银航空航运金融租赁有限公司"
    - "招商信诺人寿保险有限公司"
    - "招商信诺资产管理有限公司"
    - "招商信诺健康管理有限责任公司"
    - "小诺健康科技（广州）有限公司"
    - "招商基金管理有限公司"
    - "招商财富资产管理有限公司"
    - "大连金石高尔夫俱乐部有限公司"
    - "深圳市金尊投资发展有限公司"
    - "招银云创信息技术有限公司"
    - "深圳市汇合发展有限公司"
    - "深圳市鹏悦商业管理有限公司"
    - "招银金融信息服务（深圳）有限公司"
    - "上海招赢电子商务有限责任公司"
    - "招云（深圳）信息技术有限公司"
    - "深圳市时代华尔广告有限公司"
    - "深圳市勤和投资发展有限公司"
    - "招银金融控股（深圳）有限公司"
    - "招银金融控股（深圳）有限公司"
    - "招银国际资本管理（深圳）有限公司"
    - "招商永隆银行有限公司"
    - "招商永隆信息技术（深圳）有限公司"
    - "招商永隆股权投资管理（深圳）有限公司"
    - "招商永隆资产管理有限公司"
    - "深圳市银通智汇信息服务有限公司"
    - "深圳招招网络科技有限公司"
    - "铁建宏图（天津）投资管理有限公司"
    - "深圳聚沙成塔资产管理有限公司"
    - "深圳市鑫麦穗投资管理有限公司"
    # 目标域名:xxx.com,xxx.com,xxx.com
  域名:
    - "cmbchina.com:招商银行股份有限公司"
    - "cmbchinawm.com:招银理财有限责任公司"
    - "mucfc.com:招联消费金融股份有限公司"
    - "cmb-leasing.com:招银金融租赁有限公司"
    - "cignacmb.com:招商信诺人寿保险有限公司"
    - "cignacmbamc.com:招商信诺资产管理有限公司"
    - "cignacmbhealth.com:招商信诺健康管理有限责任公司"
    - "cmfchina.com:招商基金管理有限公司"
    - "cmwachina.com:招商财富资产管理有限公司"
    - "jinzuntz.com:深圳市金尊投资发展有限公司"
    - "cmbyc.com:招银云创信息技术有限公司"
    - "cmbi.com.hk:招银金融控股（深圳）有限公司"
    - "cmbi.info:招银金融控股（深圳）有限公司"
    - "cmbi.site:招银国际资本管理（深圳）有限公司"
    - "winglungbank.com:招商永隆银行有限公司"
    - "cmbwinglungbank.com:招商永隆股权投资管理（深圳）有限公司"
    - "cmbfae.com:深圳市银通智汇信息服务有限公司"
  ip:
    - ""
  cert:
  city:
    - ""
  #默认是或的关系，在个别里面加&&可以实现语句与关系
  gobal_keyword:
    - "招商银行"
    - "招银"
    - "招商&&资金"
    - "招商&&财富"
    - "招商&&银行"
    - "银行&&永隆"
    - "招银&&租赁"

自定义扫描:
  # 语法自定义:
  #  - body="kkkkkk"
  #  - title="kkkkkk"
  fofa:
    - #为了方便回溯归属，注意用Findyou分割
    - ""
  hunter:
    -
    -
    -
  quake:
    - ""
    -

其他扫描选项:
  跳过配置从数据库扫描: false
  生成扩展的domainsearch: true