目标:
  名称:
    - "中石油"
    # 目标域名:xxx.com,xxx.com,xxx.com
  域名:
    -
  ip:
    - ""
  cert:
  city:
    - ""
  gobal_keyword:
    - "石油"
    - "石化"

自定义扫描:
  # 语法自定义:
  #  - body="kkkkkk"
  #  - title="kkkkkk"
  fofa:
    - #为了方便回溯归属，注意用Findyou分割
    - ""
  hunter:
    -
    -
    -
  quake:
    - ""
    -
  递归搜索等级: 2

其他扫描选项:
  跳过配置从数据库扫描: false

