目标:
  名称:
    - "xx银行股份有限公司"
    # 目标域名:xxx.com,xxx.com,xxx.com
  域名:
    - "xxx.com:xx银行股份有限公司"
  ip:
    - ""
  cert:
  city:
    - ""
  #默认是或的关系，在个别里面加&&可以实现语句与关系
  gobal_keyword:
    - "银行"
    - "金融系统"
    - "银行&&资金"

自定义扫描:
  # 语法自定义:
  #  - body="kkkkkk"
  #  - title="kkkkkk"
  fofa:
    - #为了方便回溯归属，注意用Findyou分割
    - ""
  hunter:
    -
    -
    -
  quake:
    - ""
    -

其他扫描选项:
  跳过配置从数据库扫描: false
  生成扩展的domainsearch: true