id: workflowstruct-rb

info:
  name: Ruby Configuration File - Detect
  author: DhiyaneshDK
  severity: unknown
  description: Multiple Ruby configuration files were detected.
  metadata:
    verified: true
    max-request: 3
    shodan-query: html:"workflowstruct.rb"
  tags: ruby,devops,exposure,workflowstruct

http:
  - method: GET
    path:
      - "{{BaseURL}}/workflowstruct.rb"
      - "{{BaseURL}}/.chef/workflowstruct.rb"
      - "{{BaseURL}}/assets/workflowstruct.rb"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'images_dir'
          - 'css_dir'
        condition: and

      - type: status
        status:
          - 200

# digest: 490a004630440220143e13d46082d7ed7e518e94f834c7c19f98e13e254357874c0fae82ab5e963602207eb62d11046591181191c1cc4233dace456ed0dbd8d5c8244e3eb4bed96a85de:922c64590222798bb761d5b6d8e72950
