目标:
  名称:
    - "行吟信息科技"
    - "宁智信息"
    - "薯一薯二"
    - "书刻信息科技"
    - "上海影泓网络科技"
    - "河南省景禾文化传播"
    - "璞真乡里"
    - "睿德教育科技"
    -
    -
    # 目标域名:xxx.com,xxx.com,xxx.com
  域名:
    - "xiaohongshu.com"
    - "shuyishuerr.com"
    - "shuyishuer.net"
    - "littleredshop.cn"
    -
    # 目标ip:1.1.1.1,1.1.1.1/24
  ip:
    - ""
  cert:
  city:
    - "上海"
  gobal_keyword:
    - "运营"
    - "行吟"
    - "小红书"
    - "短视频"
    - "直播"
    - "UGC内容"
    - "关注"
    - "蒲公英"

公司架构设置:
  占股子公司比例: 50
  全资控股公司是否递归查找: true
  递归等级: 3

自定义扫描:
  # 语法自定义:
  #  - body="kkkkkk"
  #  - title="kkkkkk"
  fofa:
    -
  hunter:
    -
    -
    -
  quake:
    - ""
    -
  递归搜索等级: 2

其他扫描选项:
  Poc启用: false
  指定漏洞: ""
  跳过配置从数据库扫描: true
  域名联想收集: true

