#各个模块的启动/关闭
module:
  fofasearch: true
  huntersearch: true
  quakesearch: true
  cdncheck: true
  domainbrute: true
  aliveandpassivityscan: true
  dirbrute: true
  fingerprint: true
  #pocscan未实现
  pocscan: true

api:
  searchPageSize: 100
  searchLimitCount: 1000
  fofa:
    #key: xxx@163.com:1111111
    key:
  icp:
    key: ""
  quake:
    key: ""
  hunter:
    key: ""
#cdn检测并发数量
cdnconfig:
  threads: 500

#web探测
httpx:
  HTTPProxy: ""
  WebThreads: 200
  WebTimeout: 10
#指纹识别配置
fingerprint:
  dirsearch: true
  customdir:
    - "/login"
    - "/test"
    - "/admin"
  screenshot: true
  #fingerprintx是探测协议的，未实现
  fingerprintx: true

#nuclei配置，暂未实现漏扫
nuclei:
  Threads: 10

proxy:
  host: []

mysql:
  host: 127.0.0.1
  port: 3306
  name: Findyou
  username: findyou
  password: findyou

redis:
  host: 127.0.0.1:6379
  password: findyou