api:
  searchPageSize: 100
  searchLimitCount: 1000
  fofa:
    #key: yiheng6221@163.com:093208d32a4b0202b925240b81e9b739
  key: ying.hu@qingteng.cn:00954c8731415dfe6cd7f97820c4ce10
  icp:
    key: ""
  quake:
    key: ""
  hunter:
    key: ""
portscan:
  ping: false
  port: --top-ports 1000
  rate: 1000
  tech: -sS
  cmdbin: nmap
cdnconfig:
  threads: 500
httpx:
  HTTPProxy: ""
  WebThreads: 200
  WebTimeout: 10
fingerprint:
  dirsearch: true
  customdir:
    - "/login"
    - "/test"
    - "/admin"
  screenshot: true
  fingerprinthub: true
  iconhash: true
  fingerprintx: true

nuclei:
  Threads: 10

domainscan:
  resolver: resolver.txt
  wordlist: subnames.txt
  providerConfig: provider-workflowstruct.yml
  subfinder: true
  subdomainBrute: true
  subdomainCrawler: false
  ignoreCDN: false
  ignoreOutofChina: true
  portscan: false
  whois: true
  icp: true

proxy:
  host: []

mysql:
  host: 127.0.0.1
  port: 3306
  name: Findyou
  username: nbanb
  password: nbanbpro

redis:
  host: 127.0.0.1:6379
  password: nbanbpro

onlineapi:
  fofa: true
  quake: false
  hunter: false