module:
  fofasearch: true
  huntersearch: false
  quakesearch: false
  cdncheck: true
  subdomainbrute: false
  aliveandpassivityscan: true
  dirbrute: true
  fingerprint: true
  pocscan: true
  
api:
  searchPageSize: 100
  searchLimitCount: 1000
  fofa:
    key: yiheng6221@163.com:73a981a7b5b4959fa50588051444021c
  #key: ying.hu@qingteng.cn:00954c8731415dfe6cd7f97820c4ce10
  icp:
    key: ""
  quake:
    key: "035c1bd9-0ac4-4a0f-a23b-42cb8c6abb5c"
  hunter:
    key: "ced8fd312475a35afd76cc07ea7b54ec977216a96b7ca6e34b578d62f7f411af"
portscan:
  ping: false
  port: --top-ports 1000
  rate: 1000
  tech: -sS
  cmdbin: nmap
cdnconfig:
  threads: 500
httpx:
  HTTPProxy: ""
  WebThreads: 100
  WebTimeout: 10
fingerprint:
  dirsearch: true
  screenshot: true
  fingerprinthub: true
  fingerprintx: true

nuclei:
  Threads: 10

domainscan:
  resolver: resolver.txt
  wordlist: subnames.txt
  providerConfig: provider-workflowstruct.yml
  subfinder: true
  subdomainBrute: true
  subdomainCrawler: false
  ignoreCDN: false
  ignoreOutofChina: true
  portscan: false
  whois: true
  icp: true

proxy:
  host: []

mysql:
  host: 127.0.0.1
  port: 3306
  name: Findyou
  username: nbanb
  password: nbanbpro

redis:
  host: 127.0.0.1:6379
  password: nbanbpro